
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(f){var a=0;return function(){return a<f.length?{done:!1,value:f[a++]}:{done:!0}}};$jscomp.arrayIterator=function(f){return{next:$jscomp.arrayIteratorImpl(f)}};$jscomp.makeIterator=function(f){var a="undefined"!=typeof Symbol&&Symbol.iterator&&f[Symbol.iterator];return a?a.call(f):$jscomp.arrayIterator(f)};$jscomp.arrayFromIterator=function(f){for(var a,k=[];!(a=f.next()).done;)k.push(a.value);return k};
$jscomp.arrayFromIterable=function(f){return f instanceof Array?f:$jscomp.arrayFromIterator($jscomp.makeIterator(f))};
(function(f,a){window.sg=window.sg||{};window.sg.common=window.sg.common||{};window.sg.components=window.sg.components||{};var k=window.sg.common.constants.BREAKPOINTS,c=window.sg.common.utils,q=window.sg.common.exploreUtils,m=window.sg.common.$q,p=window.sg.components;p.slideShowContainer=function(){var m={htmlVideoOpen:"video-layer-open",wrap:".ex-slide-show-container",objectFit:{target:".js-object-fit",ended:"objectfit-initialized"},slideCount:{pcTotal:".ex-items-slide-card__paging-pc-total",pc:".ex-items-slide-card__paging-pc-num",
moTotal:".ex-items-slide-card__paging-mo-total",mobile:".ex-items-slide-card__paging-mo-num"},indicator:{list:".ex-slide-show-container__indicator-list",active:"s-list-on"},video:{layer:".video-area_5",videoContainer:".s-video-container",videoWrap:".s-video-wrap",layerType:".ex-items-slide-card--video-layer",playBtn:".js-video",closeBtn:".js-pop-close",layerClass:"layer-opened-mo",tempLoopClass:"js-loop-hidden",isEmbedVideo:"is-embeded-playing",isClickedId:"js-popup-id"},imgCarousel:{wrap:".js-hu-slide-show-carousel",
listItem:".ex-items-slide-card",videoClose:".js-pop-close",slideInner:".ex-items-slide-card__inner",initialized:"slick-initialized",slideCurrent:"slick-current",slideCloned:".slick-cloned",slideIndex:"data-active-index",imgWide:"slick-active--after",overReady:"js-hover-ready",slideLength:"ex-slide-show-container--item-length-",imgType:{portrait:".ex-items-slide-card--image-portrait",square:".ex-items-slide-card--image-square",landscape:".ex-items-slide-card--image-landscape"},arrow:{prev:".slick-prev",
next:".slick-next"},slickOpt:{rtl:a("html").hasClass("rtl"),slidesToShow:1,focusOnSelect:!0,touchMove:!1,speed:500,arrows:!0,variableWidth:!0,centerMode:!0,useCSS:!0,useTransform:!0,dots:!0}},textCarousel:{wrap:".js-hu-slide-card__desc-carousel",listItem:".ex-items-slide-card__desc-detail-list",textMove:"s-text-move",slickOpt:{rtl:a("html").hasClass("rtl"),speed:500,slidesToShow:1,draggable:!0,swipe:!0,touchMove:!1,dots:!1,arrows:!1,adaptiveHeight:!1,fade:!0,cssEase:"linear",responsive:[{breakpoint:k.MOBILE+
1,settings:{speed:1E3,draggable:!1,swipe:!1,adaptiveHeight:!0}}]}}};return{init:function(){q.isAemEditMode()||(this.opts=m,this.setElements(),this.setBindEvents(),this.setSlick())},setElements:function(){this.$html=a("html");this.isRtl=this.$html.hasClass("rtl");this.$body=a("body");this.isTouchDevice=this.$body.hasClass("touch-device");this.$wrap=this.$body.find(this.opts.wrap);this.wrapLength=this.$wrap.length;this.$imgCarousel=this.$wrap.find(this.opts.imgCarousel.wrap);this.imgCarouselLength=
this.$imgCarousel.length;this.$textCarousel=this.$wrap.find(this.opts.textCarousel.wrap);this.textCarouselLength=this.$textCarousel.length;this.$objectFitElement=this.$wrap.find(this.opts.objectFit.target);this.objectFitLength=this.$objectFitElement.length;this.$indicator=this.$wrap.find(this.opts.indicator.list+"\x3e button");this.$playBtn=this.$wrap.find(this.opts.video.playBtn);this.$closeBtn=this.$wrap.find(this.opts.video.closeBtn);this.loopTemplate='\x3cspan class\x3d"'+this.opts.video.tempLoopClass+
'" tabindex\x3d"0"\x3e\x3c/a\x3e';this.winWidth=c.getViewPort().width;this.setTime=null;this.runResizeTrigger=this.sliding=!1;this.arrowPosTimeout=null;this.agent=navigator.userAgent.toLowerCase();this.IECheck="Netscape"==navigator.appName&&-1!=this.agent.indexOf("trident")||-1!=this.agent.indexOf("msie")},setBindEvents:function(){this.$body.on("AEM_RESPONSIVE_CHANGE",a.proxy(this.onResponsiveChange,this));this.$body.trigger("AEM_RESPONSIVE_GET_STATUS");this.$indicator.on("click",a.proxy(this.onClickIndicator,
this));a(document).on("click",this.opts.video.playBtn,a.proxy(this.onClickVideoPlayBtn,this));this.$closeBtn.on("click",a.proxy(this.onClickVideoCloseBtn,this));a(f).on("resize orientationchange",a.proxy(this.onResize,this))},onClickVideoPlayBtn:function(b){var d=a(b.currentTarget);b=d.attr("data-vid-data")?JSON.parse(d.attr("data-vid-data")).divID:"";if(d.closest(this.opts.wrap).length&&b){var e=a("#"+b),c=e.closest(this.opts.video.layer),l=c.find(this.opts.video.videoWrap),h=c.find(this.opts.video.closeBtn);
d.css("display","none");d.parent(this.opts.video.layerType).length?(this.$body.addClass(this.opts.video.layerClass),d.attr(this.opts.video.isClickedId)||d.attr(this.opts.video.isClickedId,b),c.length&&this.setLoopEl(c,l,h)):setTimeout(a.proxy(function(){d.parent().addClass(this.opts.video.isEmbedVideo);e.find("video").length&&(e.find("video")[0].disablePictureInPicture=!0)},this),200)}},loopFocusin:function(b,d){d.preventDefault();var e=a(d.currentTarget);d=e.prev().length;e=e.next().length;!d&&b.closeBtn.length?
b.closeBtn.focus():!e&&b.videoWrap.length&&b.videoWrap.focus()},setLoopEl:function(b,d,e){if(!this.isTouchDevice){var c=d.length;c&&d.attr("tabindex",0);b.prepend(this.loopTemplate).append(this.loopTemplate);setTimeout(a.proxy(function(){c&&d.focus();b.on("focusin","."+this.opts.video.tempLoopClass,a.proxy(this.loopFocusin,this,{closeBtn:e,videoWrap:d}))},this),200)}},onClickVideoCloseBtn:function(b){b=a(b.currentTarget);var d=b.closest(this.opts.video.layer);d.closest(this.opts.wrap).length&&(d.length&&
this.$body.hasClass(this.opts.video.layerClass)?(this.$body.removeClass(this.opts.video.layerClass),d.find("."+this.opts.video.tempLoopClass).remove(),d.find(this.opts.video.videoWrap).removeAttr("tabindex"),d.off("focusin","."+this.opts.video.tempLoopClass,a.proxy(this.loopFocusin,this)),b=a("["+this.opts.video.isClickedId+"\x3d"+b.prev().prev().attr("id")+"]")):(b=b.closest(this.opts.imgCarousel.listItem).find(this.opts.video.playBtn),b.parent().removeClass(this.opts.video.isEmbedVideo)),b.length&&
b.removeAttr("style"))},embedVideoForceClose:function(b,d){var a=d?this.$body.hasClass(this.opts.htmlVideoOpen)&&b.length:b.length;if(b.closest(this.opts.wrap).length&&a){a=b.find(this.opts.video.layer);var c=b.find(this.opts.video.playBtn);b=b.find(this.opts.video.videoContainer);d&&this.$body.removeClass(this.opts.htmlVideoOpen);a.length&&(c.parent().removeClass(this.opts.video.isEmbedVideo),a.removeAttr("style"),c.length&&c.removeAttr("style"),b.length&&b.children().length&&b.children().remove())}},
onResize:function(){if(this.runResizeTrigger){var b=c.getViewPort().width,d=null,e=null,g=null,l=null;this.setArrowPosition({prev:this.$imgCarousel.find(this.opts.imgCarousel.arrow.prev),next:this.$imgCarousel.find(this.opts.imgCarousel.arrow.next)});clearTimeout(this.setTime);this.setTime=setTimeout(a.proxy(function(){for(var a=0;a<this.imgCarouselLength;a++)d=this.$imgCarousel.eq(a),l={prev:d.find(this.opts.imgCarousel.arrow.prev),next:d.find(this.opts.imgCarousel.arrow.next)},b>k.MOBILE&&d.hasClass(this.opts.imgCarousel.initialized)&&
(g=d.find("."+this.opts.imgCarousel.slideCurrent),1440<b?this.setArrow(l,"fadeIn",this.getMaxActiveSlideArrowPos(g)):this.setArrowPosition(l,g),this.runResizeTrigger=!0),d.hasClass(this.opts.imgCarousel.initialized)&&this.changeSlickOption(d),this.embedVideoForceClose(d.find(this.opts.imgCarousel.slideCloned),!1);for(a=0;a<this.textCarouselLength;a++)e=this.$textCarousel.eq(a),e.hasClass(this.opts.imgCarousel.initialized)&&e.slick("setPosition")},this),500)}else this.runResizeTrigger=!0},getMaxActiveSlideArrowPos:function(b){var a=
0;b.length&&(b.find(this.opts.imgCarousel.imgType.portrait).length?a="430":b.find(this.opts.imgCarousel.imgType.square).length?a="355":b.find(this.opts.imgCarousel.imgType.landscape).length&&(a="189"));return a},changeSlickOption:function(b){this.isMobile?(b.slick("slickSetOption","focusOnSelect",!1),b.slick("slickSetOption","speed",150),b.slick("slickSetOption","arrows",!1)):(b.slick("slickSetOption","focusOnSelect",!0),b.slick("slickSetOption","speed",500),b.slick("slickSetOption","arrows",!0))},
onResponsiveChange:function(b,d){this.isMobile="mobile"==d.RESPONSIVE_NAME?!0:!1;setTimeout(a.proxy(function(){this.objectFitHandler()},this),100)},onClickIndicator:function(b){b.preventDefault();b=a(b.currentTarget);var d=b.closest(this.opts.wrap),c=b.closest(this.opts.indicator.list);d=d.find(this.opts.imgCarousel.wrap);var g=b.parent().index();this.setIndicator(c,b.index());this.moveSlideGoTo(d,g,!1)},triggerLazyload:function(){window.sg.common.lazyLoad.setLazyLoad()},slickReinitObjectFit:function(){var b=
this.$wrap.find(this.opts.objectFit.target),a=b.length;if(a&&"string"!==typeof b.eq(0).css("object-fit")){for(var c=0;c<a;c++){var g=b.eq(c);g.hasClass(this.opts.objectFit.ended)&&g.attr("src")&&g.attr("src","")}this.$objectFitElement=this.$wrap.find(this.opts.objectFit.target);this.objectFitLength=this.$objectFitElement.length;this.objectFitHandler()}},objectImgSrcChange:function(b,a,c){a=void 0==a?"":a;setTimeout(function(){b.removeAttr("src")},100);b.css({"background-image":"url("+a+")","background-size":c}).addClass(this.opts.objectFit.ended)},
objectFitHandler:function(){if(this.objectFitLength&&"string"!==typeof this.$objectFitElement.eq(0).css("object-fit"))for(var b,a,c,g,l,h,n=0;n<this.objectFitLength;n++)b=this.$objectFitElement.eq(n),a=b.attr("src"),c=b.data("src-pc")||b.data("lazy-pc"),g=b.data("src-mobile")||b.data("lazy-mobile"),l=b.data("object-fit"),h="",c||g?!this.isMobile&&c?h=c:this.isMobile&&g&&(h=g):h=a,this.objectImgSrcChange(b,h,l)},moveSlideGoTo:function(b,a,c){b.hasClass(this.opts.imgCarousel.initialized)&&!this.sliding&&
(this.sliding=!0,b.slick("slickGoTo",a,c))},setCurrentSlickIndex:function(a,c){a.attr(this.opts.imgCarousel.slideIndex,c)},setSlideCount:function(a,c,e){e&&(a.find(this.opts.slideCount.pcTotal).text(e),a.find(this.opts.slideCount.moTotal).text(e));a.find(this.opts.slideCount.pc).text(c);a.find(this.opts.slideCount.mobile).text(c)},setIndicator:function(a,c){a.removeClass(this.opts.indicator.active);a.eq(c).addClass(this.opts.indicator.active)},setArrow:function(a,c,e){"fadeIn"==c?(a.prev.fadeIn(400),
a.next.fadeIn(400)):(a.prev.fadeOut(100),a.next.fadeOut(100))},setArrowPosition:function(a,d){a.prev.length&&a.next.length&&(d&&d.length?(this.winWidth=c.getViewPort().width,d=this.winWidth-(this.winWidth-Math.ceil(d.find(this.opts.imgCarousel.slideInner).offset().left))-50-a.prev.width(),this.setArrow(a,"fadeIn",d)):this.setArrow(a,"fadeOut"))},itemsFocusHandler:function(a,c){this.isRtl?this.IECheck&&a.scrollLeft(0):a.scrollLeft(0)},onImgCarouselEvents:function(b,d){var e=a(".ex-items-slide-card__inner").attr("data-page-track"),
g=a(".slick-current.slick-active").prevAll(),l=a(".slick-current.slick-active").nextAll();g.each(function(a,b){b.setAttribute("an-tr","ex21_article card slide-"+e+"-image-slide");b.setAttribute("an-ca","indication");b.setAttribute("an-ac","carousel");b.setAttribute("an-la","carousel:image:left")});l.each(function(a,b){b.setAttribute("an-tr","ex21_article card slide-"+e+"-image-slide");b.setAttribute("an-ca","indication");b.setAttribute("an-ac","carousel");b.setAttribute("an-la","carousel:image:right")});
if("init"==b)d.on(b,a.proxy(function(b,c){b=a(c.$slides);var d=b.eq(0),g=d.closest(this.opts.wrap),l=g.find(this.opts.indicator.list),h={prev:a(c.$prevArrow),next:a(c.$nextArrow)};a(c.$prevArrow).attr("an-tr","ex21_article card slide-"+e+"-image-arrow");a(c.$prevArrow).attr("an-ca","indication");a(c.$prevArrow).attr("an-ac","carousel");a(c.$prevArrow).attr("an-la","carousel:arrow:left");a(c.$nextArrow).attr("an-tr","ex21_article card slide-"+e+"-image-arrow");a(c.$nextArrow).attr("an-ca","indication");
a(c.$nextArrow).attr("an-ac","carousel");a(c.$nextArrow).attr("an-la","carousel:arrow:right");a(".slick-dots li").each(function(a,b){b.querySelector("button").setAttribute("an-tr","ex21_article card slide-"+e+"-image-index");b.querySelector("button").setAttribute("an-ca","indication");b.querySelector("button").setAttribute("an-ac","carousel");b.querySelector("button").setAttribute("an-la","carousel:index:"+(a+1))});b.on("focusout",a.proxy(this.itemsFocusHandler,this,a(c.$list)));this.setCurrentSlickIndex(g,
"0");this.setSlideCount(g,"1",b.length);this.setIndicator(l,0);setTimeout(a.proxy(this.slickReinitObjectFit,this),100);setTimeout(a.proxy(this.triggerLazyload,this),100);1440<this.winWidth?this.setArrow(h,"fadeIn",this.getMaxActiveSlideArrowPos(d)):this.isMobile?(h.prev.css("display","none"),h.next.css("display","none"),setTimeout(a.proxy(function(){this.changeSlickOption(a(c.$slider))},this),200)):setTimeout(a.proxy(function(){this.setArrowPosition(h,d)},this),600)},this));else d.on(b,a.proxy(function(b,
d,e,g){var l=a(d.$slides),h=null,f=null;h=null;var m=0,k={prev:null,next:null};"beforeChange"==b.type?e!=g&&(f=l.eq(e),h=f.closest(this.opts.wrap),h=h.find(this.opts.indicator.list),k.prev=a(d.$prevArrow),k.next=a(d.$nextArrow),this.setIndicator(h,g),this.embedVideoForceClose(f,!0),a(d.$slider).removeClass(this.opts.imgCarousel.overReady),0==e&&g==l.length-1&&setTimeout(a.proxy(function(){f.prev().addClass(this.opts.imgCarousel.slideCurrent)},this),50),e==l.length-1&&0==g&&setTimeout(a.proxy(function(){f.next().addClass(this.opts.imgCarousel.slideCurrent)},
this),50),this.isMobile||this.setArrowPosition(k)):"afterChange"==b.type&&(f=l.eq(e),h=f.closest(this.opts.wrap),k.prev=a(d.$prevArrow),k.next=a(d.$nextArrow),m=parseInt(h.attr(this.opts.imgCarousel.slideIndex))||0,this.sliding=!1,m!=e&&(h.find(this.opts.imgCarousel.slideCloned).removeClass(this.opts.imgCarousel.slideCurrent),this.setCurrentSlickIndex(h,e),this.setSlideCount(h,e+1),setTimeout(a.proxy(this.triggerLazyload,this),100),1440<c.getViewPort().width?(clearTimeout(this.arrowPosTimeout),this.arrowPosTimeout=
setTimeout(a.proxy(function(){this.setArrow(k,"fadeIn",this.getMaxActiveSlideArrowPos(f));a(d.$slider).addClass(this.opts.imgCarousel.overReady)},this),200)):this.isMobile?(clearTimeout(this.arrowPosTimeout),this.arrowPosTimeout=setTimeout(a.proxy(function(){a(d.$slider).addClass(this.opts.imgCarousel.overReady)},this),200)):(clearTimeout(this.arrowPosTimeout),this.arrowPosTimeout=setTimeout(a.proxy(function(){this.setArrowPosition(k,f);a(d.$slider).addClass(this.opts.imgCarousel.overReady)},this),
200))))},this))},onTextCarouselEvents:function(b,c){if("init"==b)c.on(b,a.proxy(function(b,c){var d=this.opts.textCarousel.textMove,e=a(c.$slides).eq(0);e.removeClass(d);setTimeout(a.proxy(function(){e.siblings().removeClass(d)},this),700)},this));else c.on(b,a.proxy(function(b,c,d,h){var e=this.opts.textCarousel.textMove,g=a(c.$slides);"beforeChange"==b.type?d!=h&&(g.removeClass(e),setTimeout(function(){g.eq(h).addClass(e)},150)):this.sliding=!1},this))},setSlick:function(){for(var a,c,e,g,f,h=0,
k=0;h<this.wrapLength;h++)a=this.$wrap.eq(h),e=a.find(this.opts.imgCarousel.wrap),g=a.find(this.opts.textCarousel.wrap),c=e.find(this.opts.imgCarousel.listItem),f=c.length,a.removeClass(this.opts.imgCarousel.slideLength+"5"),1<=f&&(a.addClass(this.opts.imgCarousel.slideLength+f),e.addClass(this.opts.imgCarousel.overReady),1==f?(k++,c.eq(0).addClass(this.opts.imgCarousel.slideCurrent)):(this.opts.imgCarousel.slickOpt.slidesToShow=3<f?3:1,this.onImgCarouselEvents("init",e),e.slick(this.opts.imgCarousel.slickOpt),
!g.hasClass(this.opts.imgCarousel.initialized)&&1<g.find(this.opts.textCarousel.listItem).length&&(e.slick("slickSetOption","asNavFor",g),this.onTextCarouselEvents("init",g),g.slick(this.opts.textCarousel.slickOpt),g.slick("slickSetOption","asNavFor",e),this.onTextCarouselEvents("beforeChange afterChange",g)),this.onImgCarouselEvents("beforeChange afterChange",e)))}}}();m.ready(function(){return p.slideShowContainer.init()})})(window,window.jQuery);
(function(){var f=window.sg.common.$q,a=function(a){this.els={el:a,videoStartButtonEls:a.querySelectorAll(".ex-slide-show-container__btn-video-start"),layerWrapEl:a.querySelectorAll(".ex-slide-show-container__layer-wrap"),videoWrapEl:a.querySelectorAll(".ex-slide-show-container__video-wrap"),videoEls:a.querySelectorAll(".ex-slide-show-container__video-wrap .video"),videoCloseButtonEl:a.querySelectorAll(".ex-slide-show-container__btn-video-close")};this.lazyLoad=window.sg.common.lazyLoad;this.video=
window.sg.common.video;this.indicator=window.sg.common.indicator;this.getCurrentDevice=window.sg.common.utils.getCurrentDevice;this.beforeDevice=this.getCurrentDevice();this.currentPlayingVideo={};this.init()};a.prototype.init=function(){a.instances.has(this.els.el)||(a.instances.set(this.els.el,this),this.bindEvents())};a.prototype.setVideoSize=function(a){"desktop"===this.getCurrentDevice()?(this.els.videoWrapEl[a].style.width=.8*window.innerWidth+"px",this.els.videoWrapEl[a].style.height=.45*window.innerWidth+
"px",window.innerHeight<=this.els.videoWrapEl[a].offsetHeight?(this.els.videoCloseButtonEl[a].classList.add("ex-slide-show-container__btn-video-close--fixed"),this.els.videoCloseButtonEl[a].style.left=1440<=window.innerWidth?.9*window.innerWidth+16+"px":.9*window.innerWidth+16/1440*window.outerWidth+"px"):(this.els.videoCloseButtonEl[a].classList.remove("ex-slide-show-container__btn-video-close--fixed"),this.els.videoCloseButtonEl[a].removeAttribute("style"))):(this.els.videoCloseButtonEl[a].classList.remove("ex-slide-show-container__btn-video-close--fixed"),
this.els.videoWrapEl[a].style.width=window.innerWidth+"px",this.els.videoWrapEl[a].style.height=.5625*window.innerWidth+"px")};a.prototype.bindEvents=function(){var a=this;console.log("init-open");[].concat($jscomp.arrayFromIterable(this.els.videoStartButtonEls)).forEach(function(c,f){$(c).click(function(){console.log(c);document.body.style.overflowX="hidden";a.els.layerWrapEl[f].classList.add("ex-slide-show-container__layer-wrap--show");a.els.videoEls[f].style.display="block";a.setVideoSize(f);a.video.init(a.els.videoEls[f]);
console.log(a.video.init(a.els.videoEls[f])+" "+a.currentPlayingVideo.innerHTML);a.currentPlayingVideo=a.els.videoEls[f]})});[].concat($jscomp.arrayFromIterable(this.els.videoCloseButtonEl)).forEach(function(c,f){$(c).click(function(){console.log("init-close");a.els.layerWrapEl[f].classList.remove("ex-slide-show-container__layer-wrap--show");a.currentPlayingVideo.style.display="none";a.els.videoWrapEl[f].removeAttribute("style");a.video.dispose(a.currentPlayingVideo);a.currentPlayingVideo={}})})};
a.instances=new WeakMap;var k={initAll:function(){[].concat($jscomp.arrayFromIterable(document.querySelectorAll(".ex-slide-show-container"))).forEach(function(c){a.instances.has(c)||new a(c)})}};window.sg.components.articleslidescard=k;f.ready(function(){return k.initAll()})})();