var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(d){var e=0;return function(){return e<d.length?{done:!1,value:d[e++]}:{done:!0}}};$jscomp.arrayIterator=function(d){return{next:$jscomp.arrayIteratorImpl(d)}};$jscomp.makeIterator=function(d){var e="undefined"!=typeof Symbol&&Symbol.iterator&&d[Symbol.iterator];return e?e.call(d):$jscomp.arrayIterator(d)};$jscomp.arrayFromIterator=function(d){for(var e,f=[];!(e=d.next()).done;)f.push(e.value);return f};
$jscomp.arrayFromIterable=function(d){return d instanceof Array?d:$jscomp.arrayFromIterator($jscomp.makeIterator(d))};
(function(){function d(){f(g.section).target.forEach(function(a){c.instances.has(a)?c.instances.get(a).reInit():new c(a)})}var e=window.sg.common.libs,f=window.sg.common.$q,h=window.sg.common.constants.BREAKPOINTS,k=window.sg.common.utils,g={section:".floating-navigation",wrap:".floating-navigation__menu-wrap",menu:".floating-navigation__menu .floating-navigation__menu-item",menuLink:".floating-navigation__menu .floating-navigation__menu-item a",menuAct:".active",bar:".floating-navigation__menu-bar",
leftWrap:".floating-navigation__menu",leftbox:".floating-navigation__menu-list",dropBtn:".floating-navigation__headline-text",dropBtnBeforeFocus:".floating-navigation__button"},c=function(a){var b=this;this.ele={window:f(window),section:f(a),wrap:null,menu:null,actMenu:null,nowMenu:null,bar:null,leftWrap:null,leftbox:null,dropBtn:null,menuLink:null};this.setProperty();this.statePC=h.MOBILE<k.getViewPort().width;this.stateRtl="rtl"===f("body").css("direction");this.resizeTimer=this.stateMOdrop=this.menuTop=
null;this.handler={scroll:this.fixMenu.bind(this),resize:this.resize.bind(this)};this.focusLock=function(a){a.keyCode===e.keyCode.TAB_KEY&&(!0===a.shiftKey&&a.target===b.ele.menu.eq(0).find("a").target[0]?b.ele.section.find(g.dropBtnBeforeFocus).focus():setTimeout(function(){!1===a.shiftKey&&document.activeElement===b.ele.dropBtn.target[0]&&b.toggleDropDown(!0)},30))}.bind(this);this.leftScroll=null;this.leftMove=this.moveTouchEvent.bind(this);this.leftEnd=this.endTouchEvent.bind(this);this.leftPad=
this.leftMax=this.leftBefore=null;this.leftMin=0;this.rtlCheck=4;c.instances.set(a,this);this.init()};c.prototype.setProperty=function(){this.ele.wrap=this.ele.section.find(g.wrap);this.ele.menu=this.ele.section.find(g.menu);this.ele.menuLink=this.ele.section.find(g.menuLink);this.ele.actMenu=this.ele.section.find(g.menuAct);this.ele.nowMenu=this.ele.actMenu;this.ele.bar=this.ele.section.find(g.bar);this.ele.leftWrap=this.ele.section.find(g.leftWrap);this.ele.leftbox=this.ele.section.find(g.leftbox);
this.ele.dropBtn=this.ele.section.find(g.dropBtn);this.stateMOdrop=this.ele.section.hasClass("floating-navigation--mobile-dropdown");this.leftScroll=parseFloat(this.ele.leftbox.css("margin-left"));[].concat($jscomp.arrayFromIterable(this.ele.menuLink.target)).forEach(function(a){a.draggable=!1})};c.prototype.reInit=function(){this.setProperty();this.resize(!0);this.menuFocus(this.ele.actMenu.target[0]);this.bindEvents();0>this.leftMax&&this.ele.section.addClass("next")};c.prototype.menuFocus=function(a){var b=
this.ele.wrap.width();a=a.getBoundingClientRect();0>a.left?this.goScrollLeft(this.leftScroll+-1*a.left):a.left+a.width>b&&this.goScrollLeft(this.leftScroll+-1*(a.left+a.width-b))};c.prototype.barSize=function(a){a=void 0===a?!1:a;if(!this.stateMOdrop||this.statePC){var b=this.ele.nowMenu.find("a"),c=b.width();b=b.target[0].getBoundingClientRect().left;b+=0<this.leftScroll?this.leftMin:0;b+=this.leftPad;b-=this.ele.leftbox.target[0].getBoundingClientRect().left;this.stateRtl&&this.ele.leftbox.width()<
window.innerWidth&&(b-=this.rtlCheck);this.stateRtl&&""===this.ele.leftbox.target[0].style.right&&(b=this.statePC?b+(this.leftMax-this.leftMin):b+this.leftMax);c={left:b+"px",width:c+"px"};a&&(c.transition="none",c["-o-transition"]="none",c["-ms-transition"]="none",c["-moz-transition"]="none",c["-webkit-transition"]="none");this.ele.bar.css(c);if(a){var d=this.ele.bar;setTimeout(function(){d.css({transition:"","-o-transition":"","-ms-transition":"","-moz-transition":"","-webkit-transition":""})},
30)}}};c.prototype.toggleDropDown=function(a){this.stateMOdrop&&((void 0===a?0:a)||this.ele.section.hasClass("floating-navigation--opened")?(this.clearScrollLeft(),this.ele.section.removeClass("floating-navigation--opened"),document.body.style.overflow="",this.ele.section.off("keydown",this.focusLock)):(this.ele.section.addClass("floating-navigation--opened"),document.body.style.overflow="hidden",this.ele.menu.eq(0).find("a").focus(),this.ele.section.on("keydown",this.focusLock)))};c.prototype.initDropDown=
function(){this.stateMOdrop&&!this.statePC?null===this.ele.wrap.attr("role")&&(this.ele.wrap.attr("id","floating-nav-panel"),this.ele.wrap.attr("role","region"),this.ele.wrap.attr("aria-labelledby","floating-nav-btn"),this.ele.dropBtn.attr("data-open-title","Click to open menu"),this.ele.dropBtn.attr("data-close-title","Click to close menu"),this.ele.dropBtn.attr("role","button"),this.ele.dropBtn.attr("aria-expanded","false"),this.ele.dropBtn.attr("aria-controls","floating-nav-panel"),this.ele.dropBtn.attr("id",
"floating-nav-btn"),this.ele.dropBtn.append('\x3cspan class\x3d"hidden"\x3eMenu\x3c/span\x3e'),this.ele.section.find(".floating-navigation__headline-text").attr("tabindex","0")):h.MOBILE<k.getViewPort().width&&null!==this.ele.wrap.attr("role")&&(this.ele.wrap.removeAttr("id","floating-nav-panel"),this.ele.wrap.removeAttr("role","region"),this.ele.wrap.removeAttr("aria-labelledby","floating-nav-btn"),this.ele.dropBtn.removeAttr("data-open-title","Click to open menu"),this.ele.dropBtn.removeAttr("data-close-title",
"Click to close menu"),this.ele.dropBtn.removeAttr("role","button"),this.ele.dropBtn.removeAttr("aria-expanded","false"),this.ele.dropBtn.removeAttr("aria-controls","floating-nav-panel"),this.ele.dropBtn.removeAttr("id","floating-nav-btn"),this.ele.dropBtn.find(".hidden").remove(),this.ele.section.find(".floating-navigation__headline-text").removeAttr("tabindex"))};c.prototype.init=function(){this.resize(!0);this.menuFocus(this.ele.actMenu.target[0]);this.bindEvents();0>this.leftMax&&this.ele.section.addClass("next")};
c.prototype.resize=function(){var a=this;this.statePC=h.MOBILE<k.getViewPort().width;this.leftMax=this.ele.wrap.width()-this.ele.leftbox.width();this.leftPad=parseFloat(this.ele.nowMenu.find("a").css("padding-left"));var b=this.leftScroll<this.leftMax;this.statePC?((b||this.stateRtl)&&this.goScrollLeft(this.leftMax),this.toggleDropDown(!0)):this.stateMOdrop||(b||this.stateRtl)&&this.goScrollLeft(this.leftMax);this.barSize(!0);this.initDropDown();this.fixMenu(!0);clearTimeout(this.resizeTimer);this.resizeTimer=
null;this.resizeTimer=setTimeout(function(){a.stateRtl&&(a.rtlCheck=parseInt(a.ele.leftbox.css("padding-right"),10));a.barSize(!0)},200)};c.prototype.startTouchEvent=function(a){this.stateRtl&&""===this.ele.leftbox.target[0].style.right&&(this.goScrollLeft(this.leftMax),this.barSize(!0));this.ele.leftbox.finish();this.leftBefore=void 0!==a.screenX?a.screenX:a.touches[0].screenX;this.ele.window.on("touchmove",this.leftMove);this.ele.window.on("touchend",this.leftEnd);this.ele.window.on("mousemove",
this.leftMove);this.ele.window.on("mouseup",this.leftEnd)};c.prototype.moveTouchEvent=function(a){a=void 0!==a.screenX?a.screenX:a.touches[0].screenX;this.goScrollLeft(this.leftScroll+(a-this.leftBefore));this.leftBefore=a};c.prototype.endTouchEvent=function(){this.leftBefore=null;this.ele.window.off("touchmove",this.leftMove);this.ele.window.off("touchend",this.leftEnd);this.ele.window.off("mousemove",this.leftMove);this.ele.window.off("mouseup",this.leftEnd)};c.prototype.clearScrollLeft=function(){this.ele.section.removeClass("prev");
this.ele.section.removeClass("next");this.ele.leftbox.css({marginLeft:"",right:"",left:""});this.ele.bar.css({marginLeft:""});this.leftScroll=0};c.prototype.goScrollLeft=function(a){this.stateMOdrop&&!this.statePC||0<this.leftMax?this.clearScrollLeft():(a>=this.leftMin?(a=this.leftMin,this.ele.section.removeClass(this.stateRtl?"next":"prev")):a<=this.leftMax?(a=this.leftMax,this.ele.section.removeClass(this.stateRtl?"prev":"next")):(this.ele.section.addClass("prev"),this.ele.section.addClass("next")),
this.ele.bar.css({marginLeft:0<a?"":a+"px"}),this.ele.leftbox.css({right:"auto",left:"0",marginLeft:a+"px"}),this.leftScroll=a)};c.prototype.fixMenu=function(a){var b=document.body.scrollTop||document.documentElement.scrollTop;if(void 0===a?0:a)this.ele.section.removeClass("floating-navigation--fixed"),this.menuTop=this.ele.section.target[0].getBoundingClientRect().top+b;a=this.ele.section.hasClass("floating-navigation--fixed");this.menuTop<b?a||this.ele.section.addClass("floating-navigation--fixed"):
a&&this.ele.section.removeClass("floating-navigation--fixed")};c.prototype.bindEvents=function(){var a=this;this.ele.menu.off("mouseenter").on("mouseenter",function(b){a.ele.nowMenu.target[0]!==b.currentTarget&&(a.ele.nowMenu=f(b.currentTarget),a.barSize())});this.ele.section.off("mouseleave").on("mouseleave",function(){a.ele.nowMenu=a.ele.actMenu;a.barSize()});this.ele.menuLink.off("focus").on("focus",function(b){null===a.leftBefore&&(a.ele.leftWrap.target[0].scrollLeft=a.stateRtl?-1*a.leftScroll:
a.leftMax-a.leftScroll,a.ele.nowMenu.target[0]!==b.currentTarget&&(a.ele.nowMenu=f(b.currentTarget).closest(g.menu),a.barSize()),a.menuFocus(b.currentTarget))});this.ele.leftbox.off("touchstart").on("touchstart",this.startTouchEvent.bind(this));this.ele.leftbox.off("mousedown").on("mousedown",this.startTouchEvent.bind(this));this.ele.section.off("focusout").on("focusout",function(){a.ele.nowMenu=a.ele.actMenu;a.barSize()});this.ele.window.off("scroll",this.handler.scroll).on("scroll",this.handler.scroll);
this.ele.window.off("resize",this.handler.resize).on("resize",this.handler.resize);this.stateMOdrop&&(this.ele.dropBtn.off("click").on("click",function(){a.statePC||a.toggleDropDown()}),this.ele.dropBtn.off("keyup").on("keyup",function(b){a.statePC||b.keyCode!==e.keyCode.ENTER||a.toggleDropDown()}))};c.instances=new WeakMap;window.sg.components.floatingNavigation={reInit:d};f.ready(d);f.load(d)})();