var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(d){var g=0;return function(){return g<d.length?{done:!1,value:d[g++]}:{done:!0}}};$jscomp.arrayIterator=function(d){return{next:$jscomp.arrayIteratorImpl(d)}};$jscomp.makeIterator=function(d){var g="undefined"!=typeof Symbol&&Symbol.iterator&&d[Symbol.iterator];return g?g.call(d):$jscomp.arrayIterator(d)};$jscomp.arrayFromIterator=function(d){for(var g,k=[];!(g=d.next()).done;)k.push(g.value);return k};
$jscomp.arrayFromIterable=function(d){return d instanceof Array?d:$jscomp.arrayFromIterator($jscomp.makeIterator(d))};
(function(){function d(){f&&g(f)}function g(b){for(var a={$jscomp$loop$prop$i$1:0};a.$jscomp$loop$prop$i$1<b.length;a={$jscomp$loop$prop$i$1:a.$jscomp$loop$prop$i$1},a.$jscomp$loop$prop$i$1++)q[a.$jscomp$loop$prop$i$1]=f[a.$jscomp$loop$prop$i$1].querySelector(".tab"),h[a.$jscomp$loop$prop$i$1]=e(f[a.$jscomp$loop$prop$i$1]).find(".showcase-card-tab__card-items .showcase-card-tab-card__full-bleed-wrap"),l[a.$jscomp$loop$prop$i$1]=e(f[a.$jscomp$loop$prop$i$1]).find(".showcase-card-tab__card-items .showcase-card-tab-card__full-bleed-wrap--video"),
r[a.$jscomp$loop$prop$i$1]=e(f[a.$jscomp$loop$prop$i$1]).find(".showcase-card-tab-card__product-description-wrap"),t[a.$jscomp$loop$prop$i$1]=e(f[a.$jscomp$loop$prop$i$1]).find(".showcase-card-tab-card__product-cta"),y[a.$jscomp$loop$prop$i$1]=e(f[a.$jscomp$loop$prop$i$1]).find(".showcase-card-tab-card__product-cta .cta"),u[a.$jscomp$loop$prop$i$1]=f[a.$jscomp$loop$prop$i$1].querySelectorAll(".showcase-card-tab-card__video-cta"),v[a.$jscomp$loop$prop$i$1]=f[a.$jscomp$loop$prop$i$1].querySelectorAll(".showcase-card-tab-card__mobile-video-play .icon"),
m[a.$jscomp$loop$prop$i$1]=f[a.$jscomp$loop$prop$i$1].querySelector(".popup-video"),q[a.$jscomp$loop$prop$i$1]&&(w[a.$jscomp$loop$prop$i$1]=f[a.$jscomp$loop$prop$i$1].querySelectorAll(".tab__item"),z[a.$jscomp$loop$prop$i$1]=f[a.$jscomp$loop$prop$i$1].querySelector(".showcase-card-tab__card-wrap"),n[a.$jscomp$loop$prop$i$1]=0,p[a.$jscomp$loop$prop$i$1]=new Swiper(z[a.$jscomp$loop$prop$i$1],{autoHeight:!0,on:{slideChange:function(a){return function(){A(a.$jscomp$loop$prop$i$1,p[a.$jscomp$loop$prop$i$1].activeIndex)}}(a),
slideChangeTransitionEnd:function(){B.setLazyLoad()}}}),C(a.$jscomp$loop$prop$i$1),k(a.$jscomp$loop$prop$i$1)),D(a.$jscomp$loop$prop$i$1),E(a.$jscomp$loop$prop$i$1)}function k(b){for(var a={$jscomp$loop$prop$j$3:0};a.$jscomp$loop$prop$j$3<w[b].length;a={$jscomp$loop$prop$j$3:a.$jscomp$loop$prop$j$3},a.$jscomp$loop$prop$j$3++)w[b][a.$jscomp$loop$prop$j$3].addEventListener("click",function(a){return function(){A(b,a.$jscomp$loop$prop$j$3)}}(a))}function D(b){h[b].target.forEach(function(a,c){e(a).on("mouseleave",
function(){r[b].target[c].classList.add("showcase-card-tab-card__product-description-wrap--show");t[b].target[c].classList.add("showcase-card-tab-card__product-cta--leave")});e(a).on("mouseover",function(){h[b].target[c].classList.add("showcase-card--hover")});e(a).on("mouseout",function(){h[b].target[c].classList.remove("showcase-card--hover")});e(a).on("focus",function(){r[b].target[c].classList.add("showcase-card-tab-card__product-description-wrap--show");t[b].target[c].classList.add("showcase-card-tab-card__product-cta--leave");
h[b].target[c].classList.add("showcase-card--hover")});e(a).on("blur",function(){h[b].target[c].classList.remove("showcase-card--hover")})});y[b].target.forEach(function(a,c){e(a).on("focus",function(){h[b].target[c].classList.add("showcase-card--hover")});e(a).on("blur",function(){h[b].target[c].classList.remove("showcase-card--hover")});e(a).on("mouseout",function(){h[b].target[c].classList.remove("showcase-card--hover")})})}function E(b){u[b]&&[].concat($jscomp.arrayFromIterable(u[b])).forEach(function(a,
c){a.addEventListener("click",function(){x.open(m[b],c,a)})});v[b]&&[].concat($jscomp.arrayFromIterable(v[b])).forEach(function(a,c){a.addEventListener("click",function(){x.open(m[b],c,a)})});l[b]&&l[b].target.forEach(function(a,c){l[b].attr("href","javascript:void(0)");a.addEventListener("click",function(){x.open(m[b],c,a)})})}function C(b){h[b].target.forEach(function(a){e(a).attr("tabindex","-1")});e(f[b]).find(".swiper-slide-active .showcase-card-tab-card__full-bleed-wrap").target.forEach(function(a){e(a).removeAttr("tabindex")})}
function A(b,a){n[b]!==a&&(n[b]=a);p[b].slideTo(n[b]);C(b);F.selectTab(q[b],p[b].activeIndex);B.setLazyLoad()}var f=document.querySelectorAll(".showcase-card-tab"),e=window.sg.common.$q,F=window.sg.common.tab,B=window.sg.common.lazyLoad,x=window.sg.common.popupVideo,q=[],w=[],z=[],p=[],h=[],l=[],n=[],t=[],y=[],r=[],u=[],v=[],m=[];window.sg.components.showcaseCardTab={init:d,reInit:function(){g(f)}};e.ready(function(){return d()})})();