var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var d=0;return function(){return d<a.length?{done:!1,value:a[d++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var d="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return d?d.call(a):$jscomp.arrayIterator(a)};$jscomp.arrayFromIterator=function(a){for(var d,f=[];!(d=a.next()).done;)f.push(d.value);return f};
$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};
(function(){var a=window.sg.common.$q,d=window.sg.common.utils,f=window.sg.common.constants.BREAKPOINTS,g=window.sg.common.lazyLoad,c=function(e){this.ele={el:e,titleCTAButton:null,contentsListItem:null,consentsListItemButton:null,carouselItem:null,cardSelector:null,selectedIndex:null,imageDesktopLists:null,imageDesktopImageLists:null,imageMobileLists:null,mobileCTALists:null,mobileShowMore:null};this.cardSwiper={};this.initialLoaded=this.isMobileChanged=!1;c.instances.set(e,this);this.init()};c.prototype.init=
function(){this.setElement();this.bindEvent();this.resize()};c.prototype.reInit=function(){this.removeActive();this.bindEvent();this.resize()};c.prototype.setElement=function(){this.ele.titleCTAButton=this.ele.el.querySelector(".teaser-list__title-button \x3e .cta");this.ele.contentsListItem=this.ele.el.querySelectorAll(".teaser-list__list-item");this.ele.consentsListItemButton=this.ele.el.querySelectorAll(".teaser-list__list-item \x3e .teaser-list__list-item-button");this.ele.carouselItem=this.ele.el.querySelectorAll(".teaser-list__carousel");
this.ele.cardSelector=this.ele.el.querySelectorAll(".teaser-list__image-area");this.ele.selectedIndex=0;this.ele.imageDesktopLists=this.ele.el.querySelectorAll(".teaser-list__image-inner-desktop");this.ele.imageDesktopImageLists=this.ele.el.querySelectorAll(".teaser-list__image-inner-desktop \x3e .teaser-list__desktop-image-wrap \x3e .image");this.ele.imageMobileLists=this.ele.el.querySelectorAll(".teaser-list__image-inner-mobile a");this.ele.mobileCTALists=this.ele.el.querySelectorAll(".teaser-list__mobile-button \x3e .cta");
this.ele.mobileShowMore=this.ele.el.querySelector(".show-more-anchor");this.isMobileChanged=!1;this.initialLoaded=!0};c.prototype.removeActive=function(){0!==this.ele.selectedIndex&&(this.ele.contentsListItem[this.ele.selectedIndex].classList.remove("teaser-list__list-item--active"),this.ele.consentsListItemButton[this.ele.selectedIndex].classList.remove("teaser-list__list-item-button--active"),this.ele.carouselItem[this.ele.selectedIndex].classList.remove("teaser-list__carousel--selected"),this.ele.imageDesktopLists[this.ele.selectedIndex].style.opacity=
0,this.ele.imageDesktopLists[this.ele.selectedIndex].style.zIndex=1,this.ele.imageDesktopImageLists[this.ele.selectedIndex].style.opacity=0,this.ele.imageDesktopImageLists[this.ele.selectedIndex].style.zIndex=1,this.ele.imageMobileLists[this.ele.selectedIndex].setAttribute("tabindex",-1),this.ele.imageMobileLists[this.ele.selectedIndex].setAttribute("aria-hidden",!1),this.ele.mobileCTALists[this.ele.selectedIndex].setAttribute("tabindex",-1),this.ele.mobileCTALists[this.ele.selectedIndex].setAttribute("aria-hidden",
!1))};c.prototype.bindEvent=function(){for(var e=this,b={$jscomp$loop$prop$i$3:0};b.$jscomp$loop$prop$i$3<this.ele.contentsListItem.length;b={$jscomp$loop$prop$i$3:b.$jscomp$loop$prop$i$3},b.$jscomp$loop$prop$i$3++)this.ele.contentsListItem[b.$jscomp$loop$prop$i$3].addEventListener("mouseover",function(a){return function(){e.goToSlide(a.$jscomp$loop$prop$i$3)}}(b)),this.ele.contentsListItem[b.$jscomp$loop$prop$i$3].addEventListener("focus",function(a){return function(){e.goToSlide(a.$jscomp$loop$prop$i$3)}}(b)),
this.ele.imageDesktopLists[b.$jscomp$loop$prop$i$3].addEventListener("focus",function(a){return function(){e.goToSlide(a.$jscomp$loop$prop$i$3)}}(b));this.ele.mobileShowMore.addEventListener("focus",function(){e.cardSwiper.slideNext()});this.goToSlide(0);a(window).on("resize",function(){e.resize()})};c.prototype.goToSlide=function(a){this.ele.selectedIndex!==a?(this.ele.contentsListItem[this.ele.selectedIndex].classList.remove("teaser-list__list-item--active"),this.ele.consentsListItemButton[this.ele.selectedIndex].classList.remove("teaser-list__list-item-button--active"),
this.ele.carouselItem[this.ele.selectedIndex].classList.remove("teaser-list__carousel--selected"),this.ele.carouselItem[this.ele.selectedIndex].setAttribute("aria-selected",!1),this.ele.imageDesktopLists[this.ele.selectedIndex].setAttribute("aria-hidden",!0),this.ele.imageDesktopLists[this.ele.selectedIndex].style.opacity=0,this.ele.imageDesktopLists[this.ele.selectedIndex].style.zIndex=1,this.ele.imageDesktopImageLists[this.ele.selectedIndex].style.opacity=0,this.ele.imageDesktopImageLists[this.ele.selectedIndex].style.zIndex=
1,this.ele.imageMobileLists[this.ele.selectedIndex].setAttribute("tabindex",-1),this.ele.imageMobileLists[this.ele.selectedIndex].setAttribute("aria-hidden",!0),this.ele.mobileCTALists[this.ele.selectedIndex].setAttribute("tabindex",-1),this.ele.mobileCTALists[this.ele.selectedIndex].setAttribute("aria-hidden",!0),this.ele.selectedIndex=a,this.ele.contentsListItem[this.ele.selectedIndex].classList.add("teaser-list__list-item--active"),this.ele.consentsListItemButton[this.ele.selectedIndex].classList.add("teaser-list__list-item-button--active"),
this.ele.carouselItem[this.ele.selectedIndex].classList.add("teaser-list__carousel--selected"),this.ele.carouselItem[this.ele.selectedIndex].setAttribute("aria-selected",!0),this.ele.imageDesktopLists[this.ele.selectedIndex].setAttribute("aria-hidden",!1),this.ele.imageDesktopLists[this.ele.selectedIndex].style.opacity=1,this.ele.imageDesktopLists[this.ele.selectedIndex].style.zIndex=2,this.ele.imageDesktopImageLists[this.ele.selectedIndex].style.opacity=1,this.ele.imageDesktopImageLists[this.ele.selectedIndex].style.zIndex=
2,this.ele.imageMobileLists[this.ele.selectedIndex].setAttribute("tabindex",0),this.ele.imageMobileLists[this.ele.selectedIndex].setAttribute("aria-hidden",!1),this.ele.mobileCTALists[this.ele.selectedIndex].setAttribute("tabindex",0),this.ele.mobileCTALists[this.ele.selectedIndex].setAttribute("aria-hidden",!1)):this.initialLoaded&&(this.ele.contentsListItem[this.ele.selectedIndex].classList.add("teaser-list__list-item--active"),this.ele.consentsListItemButton[this.ele.selectedIndex].classList.add("teaser-list__list-item-button--active"),
this.ele.carouselItem[this.ele.selectedIndex].classList.add("teaser-list__carousel--selected"),this.ele.carouselItem[this.ele.selectedIndex].setAttribute("aria-selected",!0),this.ele.imageDesktopLists[this.ele.selectedIndex].setAttribute("aria-hidden",!1),this.ele.imageDesktopLists[this.ele.selectedIndex].style.opacity=1,this.ele.imageDesktopLists[this.ele.selectedIndex].style.zIndex=2,this.ele.imageDesktopImageLists[this.ele.selectedIndex].style.opacity=1,this.ele.imageDesktopImageLists[this.ele.selectedIndex].style.zIndex=
2,this.ele.imageMobileLists[this.ele.selectedIndex].setAttribute("tabindex",0),this.ele.imageMobileLists[this.ele.selectedIndex].setAttribute("aria-hidden",!1),this.ele.mobileCTALists[this.ele.selectedIndex].setAttribute("tabindex",0),this.ele.mobileCTALists[this.ele.selectedIndex].setAttribute("aria-hidden",!1),this.initialLoaded=!1);this.ele.selectedIndex+1===this.ele.contentsListItem.length?(this.ele.mobileShowMore.setAttribute("tabindex",0),this.ele.mobileShowMore.setAttribute("aria-hidden",!1)):
(this.ele.mobileShowMore.setAttribute("tabindex",-1),this.ele.mobileShowMore.setAttribute("aria-hidden",!0));this.isMobileChanged&&this.cardSwiper.slideTo(this.ele.selectedIndex)};c.prototype.setMobileLayout=function(){var a=this;this.cardSwiper=new Swiper(this.ele.cardSelector,{slidesPerView:"auto",speed:300,direction:"horizontal"});this.cardSwiper.on("slideChange",function(){a.goToSlide(a.cardSwiper.activeIndex);g.setLazyLoad()});this.cardSwiper.on("slideChangeTransitionEnd",function(){g.setLazyLoad();
document.activeElement.blur()});for(var b={$jscomp$loop$prop$j$5:0};b.$jscomp$loop$prop$j$5<this.ele.carouselItem.length;b={$jscomp$loop$prop$j$5:b.$jscomp$loop$prop$j$5},b.$jscomp$loop$prop$j$5++)this.ele.carouselItem[b.$jscomp$loop$prop$j$5].addEventListener("click",function(b){return function(){a.goToSlide(b.$jscomp$loop$prop$j$5)}}(b));this.cardSwiper.slideTo(this.ele.selectedIndex)};c.prototype.setDesktopLayout=function(){this.cardSwiper.destroy();this.cardSwiper=null};c.prototype.resize=function(){this.initialLoaded&&
this.goToSlide(0);f.MOBILE<d.getViewPort().width&&this.isMobileChanged?(this.isMobileChanged=!1,this.setDesktopLayout(),this.isMobileChanged||this.goToSlide(this.ele.selectedIndex)):f.MOBILE>d.getViewPort().width&&!this.isMobileChanged&&(this.isMobileChanged=!0,this.setMobileLayout())};c.instances=new WeakMap;var h={initAll:function(){[].concat($jscomp.arrayFromIterable(document.querySelectorAll(".teaser-list"))).forEach(function(a){c.instances.has(a)||new c(a)})},reInit:function(){[].concat($jscomp.arrayFromIterable(document.querySelectorAll(".teaser-list"))).forEach(function(a){c.instances.has(a)?
c.instances.get(a).reInit():new c(a)})}};window.sg.components.teaserList=h;a.ready(h.initAll)})();